
### register
POST http://localhost:8080/api/v1/user/register
Content-Type: application/json

{
  "username": "admin",
  "password": "rahasia"
}

### login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "username": "admin",
  "password": "rahasia"
}

###
GET http://localhost:8080/api/v1/user/token
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

###
POST http://localhost:8080/api/v1/category
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

{
  "category": "Vegetables",
  "imageUrl": "notfound.png"
}

### GET CATEGORY BY ID
GET http://localhost:8080/api/v1/category/1e0a0e91-95fe-11ec-9185-8deab4502942
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### GET ALL CATEGORY
GET http://localhost:8080/api/v1/category
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### UPDATE CATEGORY
PUT http://localhost:8080/api/v1/category
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

{
  "id": "1e0a0e91-95fe-11ec-9185-8deab4502942",
  "category": "Fast food",
  "imageUrl": null
}

### DESTROY CATEGORY
DELETE http://localhost:8080/api/v1/category/a53d18cd-f9ee-11ec-b4f0-bda93bb4216c
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### SHOP
POST http://localhost:8080/api/v1/shop
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

{
  "name":"Tunas Sop",
  "imageUrl":"notfound.png",
  "address":"Jl. Soekarno Hatta No. 123"
}

### PRODUCT
POST http://localhost:8080/api/v1/product
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

{
  "name": "Carrot",
  "price": 10,
  "weight": 1000,
  "perUnit": 100,
  "description": "Good for health",
  "imageUrl" : null,
  "categoryId": "a49be6a6-e6d8-4e9e-b7e7-121f126b1de9"
}

###
PUT http://localhost:8080/api/v1/product
Content-Type: application/json

{
  "name": "BLACK",
  "id": "a3c02e8c-11d2-11ec-82a8-0242ac130003",
  "imageUrl": null,
  "price": 18500,
  "categoryId": "8c2c184e-11d2-11ec-82a8-0242ac130003"
}

### GET ALL PRODUCT
GET http://localhost:8080/api/v1/product?pageIndex=0&pageSize=10
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### DELTE PRODUCT
DELETE http://localhost:8080/api/v1/product/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### PRODUCT BY ID
GET http://localhost:8080/api/v1/product/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### PRODUCT BY CATEGORY
GET http://localhost:8080/api/v1/product/category/8c2c184e-11d2-11ec-82a8-0242ac130003

### TOP PRODUCT
POST http://localhost:8080/api/v1/product/top/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

###
GET http://localhost:8080/api/v1/product/top
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

###
GET http://localhost:8080/api/v1/product/top/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

###
DELETE http://localhost:8080/api/v1/product/top/a3c02e8c-11d2-11ec-82a8-0242ac130003

### RECOMMENDATION PRODUCT
POST http://localhost:8080/api/v1/product/recommendation
Content-Type: application/json

{
  "productId" : "a3c02e8c-11d2-11ec-82a8-0242ac130003",
  "price" : 18000
}

###
GET http://localhost:8080/api/v1/product/recommendation
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

###
DELETE http://localhost:8080/api/v1/product/recommendation/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

###
POST http://localhost:8080/api/v1/order
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

{
  "userId": "1479eca3-f0f7-4b28-b582-0809a0d36747",
  "products": [
    {
      "id": "a3c02e8c-11d2-11ec-82a8-0242ac130003",
      "imageUrl": null,
      "name": "Broccoli",
      "perUnit" : 1000,
      "weight": 1500,
      "price": 1100,
      "total": 2
    }
  ]
}

### GET TRANSACTION BY ID
GET http://localhost:8080/api/v1/order/f438b52e-996b-11ec-a3ab-173cd0023be6
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### GET TRANSACTION BY CUSTOMER ID
GET http://localhost:8080/api/v1/order/user/fc81ccd7-98aa-11ec-ba07-b78370c9a109
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### DESTROY TRANSACTION BY ID
DELETE http://localhost:8080/api/v1/order/55ebaa11-3354-11ec-9a99-53d16206a526
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### CUSTOMER
GET http://localhost:8080/api/v1/customer
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### STORE CART
POST http://localhost:8080/api/v1/cart
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

{
  "productId" : "a3c02e8c-11d2-11ec-82a8-0242ac130003",
  "price" : 18000,
  "total": 1,
  "customerId" : "ac723ce6-11d2-11ec-82a8-0242ac130003"
}

### DESTROY CART
DELETE http://localhost:8080/api/v1/cart/ac723ce6-11d2-11ec-82a8-0242ac130003/2a993110-356e-11ec-b3f6-d3d7112d1290
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### GET CUSTOMER CART
GET http://localhost:8080/api/v1/cart/ac723ce6-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### STORE WISHLIST
POST http://localhost:8080/api/v1/wishlist/ac723ce6-11d2-11ec-82a8-0242ac130003/1312ca50-179f-11ec-a7c8-395866cda754
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### GET WISHLIST
GET http://localhost:8080/api/v1/wishlist/ac723ce6-11d2-11ec-82a8-0242ac130003/1312ca50-179f-11ec-a7c8-395866cda754
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### GET CUSTOMER WISHLIST
GET http://localhost:8080/api/v1/wishlist/ac723ce6-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### DESTROY CUSTOMER WISHLIST
DELETE http://localhost:8080/api/v1/wishlist/ac723ce6-11d2-11ec-82a8-0242ac130003/1312ca50-179f-11ec-a7c8-395866cda754
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### get all user
GET http://localhost:8080/api/v1/user/all
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### grant role to user
POST http://localhost:8080/api/v1/user/role/fc81ccd7-98aa-11ec-ba07-b78370c9a109/5d3337d8-98ab-11ec-ba07-c940688411f4
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o


### revote role from user
DELETE http://localhost:8080/api/v1/user/role/1/4
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### get all roles
GET http://localhost:8080/api/v1/role/all
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### save role
POST http://localhost:8080/api/v1/role
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

{
  "name" : "USER"
}

### get role by id
GET http://localhost:8080/api/v1/role/4
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

###
GET http://localhost:8080/api/v1/user/all
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### REQUEST EXPORT PRODUCT
POST http://localhost:8080/api/v1/export/product
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

{
  "requestId": "some-request-id",
  "pageSize": 10,
  "pageIndex": 1
}

### GET ALL EXPORT STATUS
GET http://localhost:8080/api/v1/export/status?pageIndex=0&pageSize=10
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

### DOWNLOAD EXPORTED FILE
POST http://localhost:8080/api/v1/download
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o

{
  "filename": "71dc70ec-63a7-4c99-aad7-10c6a14656de.xls"
}

### GET POKEMNON
GET http://localhost:8080/api/v1/category/pokemon
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsIngtY3VzdG9tLWlkIjp7InVzZXJJZCI6IjI4NjJkMjM3LTc5ZTgtNDkxYy1iOGE1LWJmY2ZiZDBmNjRiZCJ9LCJleHAiOjE3Nzk4NDkyMTl9.e8v_xoEF5EdrUPQYkjx3etELef6iRcfAoJ92BzD466o