
### DATABASE ###
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.properties.hibernate.default_schema=main
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always

application.domain=core-service

### KAFKA ###
spring.kafka.bootstrap-servers=
messaging.outgoing.export-report-request.topic=${application.domain}-export-report-request
messaging.outgoing.export-report-result.topic=${application.domain}-export-report-result

### AWS ###
aws.region=
aws.s3.bucket.name=

### VIRTUAL THREAD ###
spring.threads.virtual.enabled=true